/**
 * world/change.ts — 將 WorldChange 應用到 WorldState，回傳新的 WorldState。
 *
 * Pure function，無 DB 依賴。不做驗證（驗證由 judgeChange 負責）。
 * 只做狀態轉換。
 */

import type { WorldState } from './state';
import type { WorldChange } from '../schemas/world-change';
import type { Constitution } from '../constitution-store';
import type { Chief } from '../chief-engine';
import type { Law } from '../law-engine';
import type { Skill } from '../skill-registry';
import type { LoopCycle } from '../loop-runner';

/**
 * 將 WorldChange 套用到 WorldState，回傳新的 state。
 * 純轉換函數 — 不做合法性檢查。
 */
export function applyChange(state: WorldState, change: WorldChange): WorldState {
  const now = new Date().toISOString();

  switch (change.type) {
    case 'constitution.supersede': {
      const oldConst = state.constitution;
      const newConst: Constitution = {
        id: `const-${crypto.randomUUID()}`,
        village_id: state.village.id,
        version: oldConst ? oldConst.version + 1 : 1,
        status: 'active',
        created_at: now,
        created_by: change.actor,
        rules: change.rules.map((r, i) => ({
          id: r.id ?? `rule-${i + 1}`,
          description: r.description,
          enforcement: r.enforcement,
          scope: r.scope,
        })),
        allowed_permissions: [...change.allowed_permissions],
        budget_limits: { ...change.budget_limits },
        superseded_by: null,
      };
      return { ...state, constitution: newConst, assembled_at: now };
    }

    case 'law.propose': {
      const newLaw: Law = {
        id: `law-${crypto.randomUUID()}`,
        village_id: state.village.id,
        proposed_by: change.proposed_by,
        approved_by: null,
        version: 1,
        status: 'proposed',
        category: change.category,
        content: change.content as Law['content'],
        risk_level: change.risk_level,
        evidence: { source: 'proposal', reasoning: 'auto-generated by applyChange' },
        effectiveness: null,
        created_at: now,
        updated_at: now,
      };
      return { ...state, active_laws: [...state.active_laws, newLaw], assembled_at: now };
    }

    case 'law.enact': {
      const laws = state.active_laws.map((l) =>
        l.id === change.law_id
          ? { ...l, status: 'active' as const, approved_by: change.approved_by, updated_at: now }
          : l,
      );
      return { ...state, active_laws: laws, assembled_at: now };
    }

    case 'law.repeal': {
      const laws = state.active_laws.filter((l) => l.id !== change.law_id);
      return { ...state, active_laws: laws, assembled_at: now };
    }

    case 'chief.appoint': {
      const newChief: Chief = {
        id: `chief-${crypto.randomUUID()}`,
        village_id: state.village.id,
        name: change.name,
        role: change.role,
        version: 1,
        status: 'active',
        skills: change.skills.map((id) => ({ skill_id: id, skill_version: 1 })),
        permissions: [...change.permissions],
        personality: change.personality ?? {
          risk_tolerance: 'moderate',
          communication_style: 'concise',
          decision_speed: 'deliberate',
        },
        constraints: [],
        created_at: now,
        updated_at: now,
      };
      return { ...state, chiefs: [...state.chiefs, newChief], assembled_at: now };
    }

    case 'chief.dismiss': {
      const chiefs = state.chiefs.filter((c) => c.id !== change.chief_id);
      return { ...state, chiefs, assembled_at: now };
    }

    case 'chief.update_permissions': {
      const chiefs = state.chiefs.map((c) =>
        c.id === change.chief_id
          ? { ...c, permissions: [...change.permissions], updated_at: now }
          : c,
      );
      return { ...state, chiefs, assembled_at: now };
    }

    case 'skill.register': {
      const newSkill: Skill = {
        id: `skill-${crypto.randomUUID()}`,
        name: change.name,
        version: 1,
        status: 'verified',
        village_id: state.village.id,
        definition: {
          ...change.definition,
          examples: change.definition.examples as { input: string; expected_output: string; explanation?: string }[],
        },
        created_at: now,
        updated_at: now,
        verified_at: now,
        verified_by: 'system',
      };
      return { ...state, skills: [...state.skills, newSkill], assembled_at: now };
    }

    case 'skill.revoke': {
      const skills = state.skills.filter((s) => s.id !== change.skill_id);
      return { ...state, skills, assembled_at: now };
    }

    case 'budget.adjust': {
      if (!state.constitution) return state;
      const limits = { ...state.constitution.budget_limits };
      if (change.max_cost_per_action !== undefined) limits.max_cost_per_action = change.max_cost_per_action;
      if (change.max_cost_per_day !== undefined) limits.max_cost_per_day = change.max_cost_per_day;
      if (change.max_cost_per_loop !== undefined) limits.max_cost_per_loop = change.max_cost_per_loop;
      return {
        ...state,
        constitution: { ...state.constitution, budget_limits: limits },
        assembled_at: now,
      };
    }

    case 'cycle.start': {
      const newCycle: LoopCycle = {
        id: `cycle-${crypto.randomUUID()}`,
        village_id: state.village.id,
        chief_id: change.chief_id,
        trigger: change.trigger,
        status: 'running',
        version: 1,
        budget_remaining: state.constitution?.budget_limits.max_cost_per_loop ?? 50,
        cost_incurred: 0,
        iterations: 0,
        max_iterations: change.max_iterations,
        timeout_ms: change.timeout_ms,
        actions: [],
        laws_proposed: [],
        laws_enacted: [],
        abort_reason: null,
        intent: null,
        created_at: now,
        updated_at: now,
      };
      return { ...state, running_cycles: [...state.running_cycles, newCycle], assembled_at: now };
    }

    case 'cycle.end': {
      const cycles = state.running_cycles.filter((c) => c.id !== change.cycle_id);
      return { ...state, running_cycles: cycles, assembled_at: now };
    }

    case 'village.update': {
      const village = { ...state.village, updated_at: now };
      if (change.name !== undefined) village.name = change.name;
      if (change.description !== undefined) village.description = change.description;
      if (change.target_repo !== undefined) village.target_repo = change.target_repo;
      if (change.metadata !== undefined) village.metadata = change.metadata;
      return { ...state, village, assembled_at: now };
    }
  }
}
