/**
 * world/change.ts — 將 WorldChange 應用到 WorldState，回傳新的 WorldState。
 *
 * Pure function，無 DB 依賴。不做驗證（驗證由 judgeChange 負責）。
 * 只做狀態轉換。
 */

import type { WorldState } from './state';
import type { WorldChange } from '../schemas/world-change';
import type { Constitution } from '../constitution-store';
import type { Chief } from '../chief-engine';
import type { Law } from '../law-engine';
import type { Skill } from '../skill-registry';
import type { LoopCycle } from '../loop-runner';

/**
 * 將 WorldChange 套用到 WorldState，回傳新的 state。
 * 純轉換函數 — 不做合法性檢查。
 */
export function applyChange(state: WorldState, change: WorldChange): WorldState {
  const now = new Date().toISOString();

  switch (change.type) {
    case 'constitution.supersede':
      return applyConstitutionSupersede(state, change, now);
    case 'law.propose':
      return applyLawPropose(state, change, now);
    case 'law.enact':
      return applyLawEnact(state, change, now);
    case 'law.repeal':
      return applyLawRepeal(state, change, now);
    case 'chief.appoint':
      return applyChiefAppoint(state, change, now);
    case 'chief.dismiss':
      return applyChiefDismiss(state, change, now);
    case 'chief.update_permissions':
      return applyChiefUpdatePermissions(state, change, now);
    case 'skill.register':
      return applySkillRegister(state, change, now);
    case 'skill.revoke':
      return applySkillRevoke(state, change, now);
    case 'budget.adjust':
      return applyBudgetAdjust(state, change, now);
    case 'cycle.start':
      return applyCycleStart(state, change, now);
    case 'cycle.end':
      return applyCycleEnd(state, change, now);
    case 'village.update':
      return applyVillageUpdate(state, change, now);
  }
}

// ---------------------------------------------------------------------------
// 各 change type 的處理函數
// ---------------------------------------------------------------------------

function applyConstitutionSupersede(
  state: WorldState,
  change: Extract<WorldChange, { type: 'constitution.supersede' }>,
  now: string,
): WorldState {
  const oldConst = state.constitution;
  const newConst: Constitution = {
    id: `const-${crypto.randomUUID()}`,
    village_id: state.village.id,
    version: oldConst ? oldConst.version + 1 : 1,
    status: 'active',
    created_at: now,
    created_by: change.actor,
    rules: change.rules.map((r, i) => ({
      id: r.id ?? `rule-${i + 1}`,
      description: r.description,
      enforcement: r.enforcement,
      scope: r.scope,
    })),
    allowed_permissions: [...change.allowed_permissions],
    budget_limits: { ...change.budget_limits },
    // Carry evaluator_rules into the new constitution
    evaluator_rules: change.evaluator_rules.length > 0 ? [...change.evaluator_rules] : undefined,
    superseded_by: null,
  };
  return { ...state, constitution: newConst, assembled_at: now };
}

function applyLawPropose(
  state: WorldState,
  change: Extract<WorldChange, { type: 'law.propose' }>,
  now: string,
): WorldState {
  const newLaw: Law = {
    id: `law-${crypto.randomUUID()}`,
    village_id: state.village.id,
    proposed_by: change.proposed_by,
    approved_by: null,
    version: 1,
    status: 'proposed',
    category: change.category,
    content: change.content as Law['content'],
    risk_level: change.risk_level,
    evidence: { source: 'proposal', reasoning: 'auto-generated by applyChange' },
    effectiveness: null,
    created_at: now,
    updated_at: now,
  };
  return { ...state, active_laws: [...state.active_laws, newLaw], assembled_at: now };
}

function applyLawEnact(
  state: WorldState,
  change: Extract<WorldChange, { type: 'law.enact' }>,
  now: string,
): WorldState {
  const laws = state.active_laws.map((l) =>
    l.id === change.law_id
      ? { ...l, status: 'active' as const, approved_by: change.approved_by, updated_at: now }
      : l,
  );
  return { ...state, active_laws: laws, assembled_at: now };
}

function applyLawRepeal(
  state: WorldState,
  change: Extract<WorldChange, { type: 'law.repeal' }>,
  now: string,
): WorldState {
  const laws = state.active_laws.filter((l) => l.id !== change.law_id);
  return { ...state, active_laws: laws, assembled_at: now };
}

function applyChiefAppoint(
  state: WorldState,
  change: Extract<WorldChange, { type: 'chief.appoint' }>,
  now: string,
): WorldState {
  const newChief: Chief = {
    id: `chief-${crypto.randomUUID()}`,
    village_id: state.village.id,
    name: change.name,
    role: change.role,
    role_type: 'chief',
    parent_chief_id: null,
    version: 1,
    status: 'active',
    skills: change.skills.map((id) => ({ skill_id: id, skill_version: 1 })),
    pipelines: [],
    permissions: [...change.permissions],
    personality: change.personality ?? {
      risk_tolerance: 'moderate',
      communication_style: 'concise',
      decision_speed: 'deliberate',
    },
    constraints: [],
    profile: null,
    adapter_type: 'local',
    context_mode: 'fat',
    adapter_config: {},
    budget_config: null,
    use_precedents: false,
    precedent_config: null,
    pause_reason: null,
    paused_at: null,
    last_heartbeat_at: null,
    current_run_id: null,
    current_run_status: 'idle',
    timeout_count: 0,
    created_at: now,
    updated_at: now,
  };
  return { ...state, chiefs: [...state.chiefs, newChief], assembled_at: now };
}

function applyChiefDismiss(
  state: WorldState,
  change: Extract<WorldChange, { type: 'chief.dismiss' }>,
  now: string,
): WorldState {
  const chiefs = state.chiefs.filter((c) => c.id !== change.chief_id);
  return { ...state, chiefs, assembled_at: now };
}

function applyChiefUpdatePermissions(
  state: WorldState,
  change: Extract<WorldChange, { type: 'chief.update_permissions' }>,
  now: string,
): WorldState {
  const chiefs = state.chiefs.map((c) =>
    c.id === change.chief_id
      ? { ...c, permissions: [...change.permissions], updated_at: now }
      : c,
  );
  return { ...state, chiefs, assembled_at: now };
}

function applySkillRegister(
  state: WorldState,
  change: Extract<WorldChange, { type: 'skill.register' }>,
  now: string,
): WorldState {
  const newSkill: Skill = {
    id: `skill-${crypto.randomUUID()}`,
    name: change.name,
    version: 1,
    status: 'verified',
    village_id: state.village.id,
    definition: {
      ...change.definition,
      examples: change.definition.examples as { input: string; expected_output: string; explanation?: string }[],
    },
    created_at: now,
    updated_at: now,
    verified_at: now,
    verified_by: 'system',
    content: null,
    source_type: 'system',
    source_origin: null,
    source_author: null,
    forked_from: null,
    scope_type: 'global',
    team_id: null,
    tags: [],
    used_count: 0,
    last_used_at: null,
  };
  return { ...state, skills: [...state.skills, newSkill], assembled_at: now };
}

function applySkillRevoke(
  state: WorldState,
  change: Extract<WorldChange, { type: 'skill.revoke' }>,
  now: string,
): WorldState {
  const skills = state.skills.filter((s) => s.id !== change.skill_id);
  return { ...state, skills, assembled_at: now };
}

function applyBudgetAdjust(
  state: WorldState,
  change: Extract<WorldChange, { type: 'budget.adjust' }>,
  now: string,
): WorldState {
  if (!state.constitution) return state;
  const limits = { ...state.constitution.budget_limits };
  if (change.max_cost_per_action !== undefined) limits.max_cost_per_action = change.max_cost_per_action;
  if (change.max_cost_per_day !== undefined) limits.max_cost_per_day = change.max_cost_per_day;
  if (change.max_cost_per_loop !== undefined) limits.max_cost_per_loop = change.max_cost_per_loop;
  return {
    ...state,
    constitution: { ...state.constitution, budget_limits: limits },
    assembled_at: now,
  };
}

function applyCycleStart(
  state: WorldState,
  change: Extract<WorldChange, { type: 'cycle.start' }>,
  now: string,
): WorldState {
  const newCycle: LoopCycle = {
    id: `cycle-${crypto.randomUUID()}`,
    village_id: state.village.id,
    chief_id: change.chief_id,
    trigger: change.trigger,
    status: 'running',
    version: 1,
    budget_remaining: state.constitution?.budget_limits.max_cost_per_loop ?? 50,
    cost_incurred: 0,
    iterations: 0,
    max_iterations: change.max_iterations,
    timeout_ms: change.timeout_ms,
    actions: [],
    laws_proposed: [],
    laws_enacted: [],
    abort_reason: null,
    intent: null,
    created_at: now,
    updated_at: now,
  };
  return { ...state, running_cycles: [...state.running_cycles, newCycle], assembled_at: now };
}

function applyCycleEnd(
  state: WorldState,
  change: Extract<WorldChange, { type: 'cycle.end' }>,
  now: string,
): WorldState {
  const cycles = state.running_cycles.filter((c) => c.id !== change.cycle_id);
  return { ...state, running_cycles: cycles, assembled_at: now };
}

function applyVillageUpdate(
  state: WorldState,
  change: Extract<WorldChange, { type: 'village.update' }>,
  now: string,
): WorldState {
  const village = { ...state.village, updated_at: now };
  if (change.name !== undefined) village.name = change.name;
  if (change.description !== undefined) village.description = change.description;
  if (change.target_repo !== undefined) village.target_repo = change.target_repo;
  if (change.metadata !== undefined) village.metadata = change.metadata;
  return { ...state, village, assembled_at: now };
}
